trigger:
- main

pool:
  name: Default  # Or the actual name of your self-hosted agent pool

steps:
- checkout: self

- script: |
    python --version
    pip --version
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

- script: |
    python -m unittest discover -s tests
  displayName: 'Run Flask Unit Tests'
