# azure-pipelines.yml

trigger:
  - main

pool:
  name: Default  # <-- your self-hosted agent pool name

steps:
- task: UsePythonVersion@0
  inputs:
    version: '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    python -m unittest discover -s tests
  displayName: 'Run Flask Unit Tests'
