trigger:
- main

pool:
  name: Default  # Use your self-hosted agent pool name

steps:
- checkout: self

- script: |
    python --version
    pip install setuptools wheel twine
    python setup.py sdist bdist_wheel
  displayName: 'Build Python Package'

- task:  TwineAuthenticate@1
  inputs:
    artifactFeed:'DevOps-Demo-WebApp/python-demo-feed'
  displayName: "Authenticate"
- script: |
    twine upload -r python-demo-feed --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Upload to Azure Artifacts'
